#!/usr/bin/env python3
"""generate_sd_code.py — 从 Safetensors 权重自动生成 StaticPy 推理代码"""
import sys, json, os

def load_index(weight_dir):
    with open(os.path.join(weight_dir, 'index.json')) as f:
        return json.load(f)

def group_by_prefix(tensors, prefix):
    groups = {}
    for t in tensors:
        name = t['name']
        if name.startswith(prefix):
            rest = name[len(prefix):].strip('.')
            parts = rest.split('.', 1)
            key = parts[0]
            if key not in groups: groups[key] = []
            groups[key].append(t)
    return groups

def generate_vae_decoder(weight_dir):
    idx = load_index(weight_dir)
    decoder = [t for t in idx if t['name'].startswith('decoder.')]
    lines = []
    lines.append("# Auto-generated by generate_sd_code.py")
    lines.append("")
    for t in decoder:
        name = t['name'].replace('decoder.', '', 1)
        safe = name.replace('.', '_')
        n = 1
        for d in t['shape']: n *= d
        lines.append(f"    {safe} = load_bin(weights_dir + '/decoder_{safe}.bin', {n})")
    lines.append("")
    lines.append("    h = conv2d(latent, conv_in_weight, conv_in_bias, n, 4, 512, h, w, 3, 1, 1)")
    lines.append("")
    for block in ['block_1', 'block_2']:
        lines.append(f"    h = group_norm(h, mid_{block}_norm1_weight, mid_{block}_norm1_bias, 32, 512, h*w)")
        lines.append(f"    arr_silu(h, h, n*512*h*w)")
        lines.append(f"    h = conv2d(h, mid_{block}_conv1_weight, mid_{block}_conv1_bias, n, 512, 512, h, w, 3, 1, 1)")
        lines.append(f"    h = group_norm(h, mid_{block}_norm2_weight, mid_{block}_norm2_bias, 32, 512, h*w)")
        lines.append(f"    arr_silu(h, h, n*512*h*w)")
        lines.append(f"    h = conv2d(h, mid_{block}_conv2_weight, mid_{block}_conv2_bias, n, 512, 512, h, w, 3, 1, 1)")
    chs = [512, 256, 128, 64]
    for stage, ch in enumerate(chs):
        blocks = group_by_prefix(decoder, f'decoder.up.{stage}')
        for key in sorted(blocks.keys()):
            if not key.startswith('block'): continue
            bn = key
            lines.append(f"    h = group_norm(h, up_{stage}_{bn}_norm1_weight, up_{stage}_{bn}_norm1_bias, 32, {ch}, h*w)")
            lines.append(f"    arr_silu(h, h, n*{ch}*h*w)")
            lines.append(f"    h = conv2d(h, up_{stage}_{bn}_conv1_weight, up_{stage}_{bn}_conv1_bias, n, {ch}, {ch}, h, w, 3, 1, 1)")
            lines.append(f"    h = group_norm(h, up_{stage}_{bn}_norm2_weight, up_{stage}_{bn}_norm2_bias, 32, {ch}, h*w)")
            lines.append(f"    arr_silu(h, h, n*{ch}*h*w)")
            lines.append(f"    h = conv2d(h, up_{stage}_{bn}_conv2_weight, up_{stage}_{bn}_conv2_bias, n, {ch}, {ch}, h, w, 3, 1, 1)")
        if stage < 3:
            next_ch = chs[stage + 1]
            lines.append(f"    h = upsample_nearest(h, n, {ch}, h, w, 2)")
            lines.append(f"    h = h * 2; w = w * 2")
            lines.append(f"    h = conv2d(h, up_{stage}_conv_weight, up_{stage}_conv_bias, n, {ch}, {next_ch}, h, w, 3, 1, 1)")
    lines.append(f"    out = conv2d(h, conv_out_weight, conv_out_bias, n, 64, 3, h, w, 3, 1, 1)")
    lines.append(f"    arr_clip(out, 0.0, 1.0, n*3*h*w)")
    lines.append(f"    return out")
    return '\n'.join(lines)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python generate_sd_code.py <weight_dir> <vae_decoder>")
        sys.exit(1)
    if sys.argv[2] == 'vae_decoder':
        print(generate_vae_decoder(sys.argv[1]))
