def main():
    a: list[float] = make_float_array(1280)
    arr_fill(a, 0.5, 1280)
    print("filled")
    t: ptr = st_from_blob_2d(a, 1, 1280)
    print("from_blob ok")
    st_tensor_free(t)
    print("done")
    exit_program(0)
main()
