# torch_ops.static.py — staticpyTorch: PyTorch C API for StaticPy
# 运行时 dlopen libtorch.so，提供 PyTorch 级别的算子
# 所有函数以 st_ 为前缀（static_torch）

extern fn st_cuda_available() -> int from "staticpy_torch"
extern fn st_conv2d(input: ptr, weight: ptr, bias: ptr,
    stride_h: int, stride_w: int, pad_h: int, pad_w: int,
    dilation_h: int, dilation_w: int, groups: int) -> ptr from "staticpy_torch"
extern fn st_linear(input: ptr, weight: ptr, bias: ptr) -> ptr from "staticpy_torch"
extern fn st_group_norm(input: ptr, num_groups: int, weight: ptr, bias: ptr, eps: float) -> ptr from "staticpy_torch"
extern fn st_layer_norm(input: ptr, weight: ptr, bias: ptr, eps: float) -> ptr from "staticpy_torch"
extern fn st_mm(a: ptr, b: ptr) -> ptr from "staticpy_torch"
extern fn st_silu(input: ptr) -> ptr from "staticpy_torch"
extern fn st_relu(input: ptr) -> ptr from "staticpy_torch"
extern fn st_gelu(input: ptr) -> ptr from "staticpy_torch"
extern fn st_sigmoid(input: ptr) -> ptr from "staticpy_torch"
extern fn st_tanh(input: ptr) -> ptr from "staticpy_torch"
extern fn st_softmax(input: ptr, dim: int) -> ptr from "staticpy_torch"
extern fn st_upsample_nearest(input: ptr, scale_h: int, scale_w: int) -> ptr from "staticpy_torch"
extern fn st_tensor_to_cpu(t: ptr) -> void from "staticpy_torch"
extern fn st_tensor_to_cuda(t: ptr) -> void from "staticpy_torch"
extern fn st_reshape(t: ptr, dims: ptr, ndim: int) -> ptr from "staticpy_torch"
extern fn st_clone(t: ptr) -> ptr from "staticpy_torch"
extern fn st_transpose(t: ptr, dim0: int, dim1: int) -> ptr from "staticpy_torch"
extern fn st_bmm(a: ptr, b: ptr) -> ptr from "staticpy_torch"
extern fn st_scaled_dot_product_attention(q: ptr, k: ptr, v: ptr, is_causal: int) -> ptr from "staticpy_torch"
extern fn st_add_tensor(a: ptr, b: ptr) -> ptr from "staticpy_torch"
extern fn st_sub_tensor(a: ptr, b: ptr) -> ptr from "staticpy_torch"
extern fn st_mul_tensor(a: ptr, b: ptr) -> ptr from "staticpy_torch"
extern fn st_mul_scalar_tensor(t: ptr, s: float) -> ptr from "staticpy_torch"
extern fn st_arange(start: int, end: int, step: int) -> ptr from "staticpy_torch"
extern fn st_cat_channel(a: ptr, b: ptr) -> ptr from "staticpy_torch"
extern fn st_cat_dim(a: ptr, b: ptr, dim: int) -> ptr from "staticpy_torch"
extern fn st_new(dims: ptr, ndim: int) -> ptr from "staticpy_torch"
extern fn st_tensor_numel(t: ptr) -> int from "staticpy_torch"
extern fn st_tensor_data(t: ptr) -> ptr from "staticpy_torch"
extern fn st_tensor_free(t: ptr) -> void from "staticpy_torch"
extern fn st_from_blob_1d(data: ptr, d0: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_2d(data: ptr, d0: int, d1: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_3d(data: ptr, d0: int, d1: int, d2: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_4d(data: ptr, d0: int, d1: int, d2: int, d3: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_half_1d(data: ptr, d0: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_half_2d(data: ptr, d0: int, d1: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_half_3d(data: ptr, d0: int, d1: int, d2: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_half_4d(data: ptr, d0: int, d1: int, d2: int, d3: int) -> ptr from "staticpy_torch"
extern fn st_from_blob_half_flat(data: ptr, n: int) -> ptr from "staticpy_torch"
extern fn st_view_1d(base: ptr, offset: int, d0: int) -> ptr from "staticpy_torch"
extern fn st_view_2d(base: ptr, offset: int, d0: int, d1: int) -> ptr from "staticpy_torch"
extern fn st_view_4d(base: ptr, offset: int, d0: int, d1: int, d2: int, d3: int) -> ptr from "staticpy_torch"
extern fn st_tensor_to_half(t: ptr) -> ptr from "staticpy_torch"
extern fn st_tensor_to_float(t: ptr) -> ptr from "staticpy_torch"
extern fn st_get(t: ptr, i: int) -> float from "staticpy_torch"
extern fn st_print_shape(t: ptr) -> void from "staticpy_torch"
extern fn st_tensor_save(t: ptr, path: str) -> void from "staticpy_torch"
extern fn st_sum(t: ptr) -> float from "staticpy_torch"
extern fn st_max(t: ptr) -> float from "staticpy_torch"
extern fn st_min(t: ptr) -> float from "staticpy_torch"
extern fn st_mean(t: ptr) -> float from "staticpy_torch"
extern fn st_cuda_empty_cache() -> void from "staticpy_torch"
extern fn st_cuda_memory_allocated() -> int from "staticpy_torch"
extern fn st_cuda_torch_memory_allocated() -> int from "staticpy_torch"
