# vae.static.py — Auto-generated VAE Decoder
# 由权重文件 /tmp/sd_weights/vae/ 自动生成

def vae_decoder_forward(latent, weights_dir, n, height, width):
    h_cur: list[float]
    h: int = height
    w: int = width

    conv_in_bias = load_bin(weights_dir + "/decoder_conv_in_bias.bin", 512)
    conv_in_weight = load_bin(weights_dir + "/decoder_conv_in_weight.bin", 73728)
    conv_out_bias = load_bin(weights_dir + "/decoder_conv_out_bias.bin", 3)
    conv_out_weight = load_bin(weights_dir + "/decoder_conv_out_weight.bin", 3456)
    mid_attn_1_k_bias = load_bin(weights_dir + "/decoder_mid_attn_1_k_bias.bin", 512)
    mid_attn_1_k_weight = load_bin(weights_dir + "/decoder_mid_attn_1_k_weight.bin", 262144)
    mid_attn_1_norm_bias = load_bin(weights_dir + "/decoder_mid_attn_1_norm_bias.bin", 512)
    mid_attn_1_norm_weight = load_bin(weights_dir + "/decoder_mid_attn_1_norm_weight.bin", 512)
    mid_attn_1_proj_out_bias = load_bin(weights_dir + "/decoder_mid_attn_1_proj_out_bias.bin", 512)
    mid_attn_1_proj_out_weight = load_bin(weights_dir + "/decoder_mid_attn_1_proj_out_weight.bin", 262144)
    mid_attn_1_q_bias = load_bin(weights_dir + "/decoder_mid_attn_1_q_bias.bin", 512)
    mid_attn_1_q_weight = load_bin(weights_dir + "/decoder_mid_attn_1_q_weight.bin", 262144)
    mid_attn_1_v_bias = load_bin(weights_dir + "/decoder_mid_attn_1_v_bias.bin", 512)
    mid_attn_1_v_weight = load_bin(weights_dir + "/decoder_mid_attn_1_v_weight.bin", 262144)
    mid_block_1_conv1_bias = load_bin(weights_dir + "/decoder_mid_block_1_conv1_bias.bin", 512)
    mid_block_1_conv1_weight = load_bin(weights_dir + "/decoder_mid_block_1_conv1_weight.bin", 2359296)
    mid_block_1_conv2_bias = load_bin(weights_dir + "/decoder_mid_block_1_conv2_bias.bin", 512)
    mid_block_1_conv2_weight = load_bin(weights_dir + "/decoder_mid_block_1_conv2_weight.bin", 2359296)
    mid_block_1_norm1_bias = load_bin(weights_dir + "/decoder_mid_block_1_norm1_bias.bin", 512)
    mid_block_1_norm1_weight = load_bin(weights_dir + "/decoder_mid_block_1_norm1_weight.bin", 512)
    mid_block_1_norm2_bias = load_bin(weights_dir + "/decoder_mid_block_1_norm2_bias.bin", 512)
    mid_block_1_norm2_weight = load_bin(weights_dir + "/decoder_mid_block_1_norm2_weight.bin", 512)
    mid_block_2_conv1_bias = load_bin(weights_dir + "/decoder_mid_block_2_conv1_bias.bin", 512)
    mid_block_2_conv1_weight = load_bin(weights_dir + "/decoder_mid_block_2_conv1_weight.bin", 2359296)
    mid_block_2_conv2_bias = load_bin(weights_dir + "/decoder_mid_block_2_conv2_bias.bin", 512)
    mid_block_2_conv2_weight = load_bin(weights_dir + "/decoder_mid_block_2_conv2_weight.bin", 2359296)
    mid_block_2_norm1_bias = load_bin(weights_dir + "/decoder_mid_block_2_norm1_bias.bin", 512)
    mid_block_2_norm1_weight = load_bin(weights_dir + "/decoder_mid_block_2_norm1_weight.bin", 512)
    mid_block_2_norm2_bias = load_bin(weights_dir + "/decoder_mid_block_2_norm2_bias.bin", 512)
    mid_block_2_norm2_weight = load_bin(weights_dir + "/decoder_mid_block_2_norm2_weight.bin", 512)
    norm_out_bias = load_bin(weights_dir + "/decoder_norm_out_bias.bin", 128)
    norm_out_weight = load_bin(weights_dir + "/decoder_norm_out_weight.bin", 128)
    up_0_block_0_conv1_bias = load_bin(weights_dir + "/decoder_up_0_block_0_conv1_bias.bin", 128)
    up_0_block_0_conv1_weight = load_bin(weights_dir + "/decoder_up_0_block_0_conv1_weight.bin", 294912)
    up_0_block_0_conv2_bias = load_bin(weights_dir + "/decoder_up_0_block_0_conv2_bias.bin", 128)
    up_0_block_0_conv2_weight = load_bin(weights_dir + "/decoder_up_0_block_0_conv2_weight.bin", 147456)
    up_0_block_0_nin_shortcut_bias = load_bin(weights_dir + "/decoder_up_0_block_0_nin_shortcut_bias.bin", 128)
    up_0_block_0_nin_shortcut_weight = load_bin(weights_dir + "/decoder_up_0_block_0_nin_shortcut_weight.bin", 32768)
    up_0_block_0_norm1_bias = load_bin(weights_dir + "/decoder_up_0_block_0_norm1_bias.bin", 256)
    up_0_block_0_norm1_weight = load_bin(weights_dir + "/decoder_up_0_block_0_norm1_weight.bin", 256)
    up_0_block_0_norm2_bias = load_bin(weights_dir + "/decoder_up_0_block_0_norm2_bias.bin", 128)
    up_0_block_0_norm2_weight = load_bin(weights_dir + "/decoder_up_0_block_0_norm2_weight.bin", 128)
    up_0_block_1_conv1_bias = load_bin(weights_dir + "/decoder_up_0_block_1_conv1_bias.bin", 128)
    up_0_block_1_conv1_weight = load_bin(weights_dir + "/decoder_up_0_block_1_conv1_weight.bin", 147456)
    up_0_block_1_conv2_bias = load_bin(weights_dir + "/decoder_up_0_block_1_conv2_bias.bin", 128)
    up_0_block_1_conv2_weight = load_bin(weights_dir + "/decoder_up_0_block_1_conv2_weight.bin", 147456)
    up_0_block_1_norm1_bias = load_bin(weights_dir + "/decoder_up_0_block_1_norm1_bias.bin", 128)
    up_0_block_1_norm1_weight = load_bin(weights_dir + "/decoder_up_0_block_1_norm1_weight.bin", 128)
    up_0_block_1_norm2_bias = load_bin(weights_dir + "/decoder_up_0_block_1_norm2_bias.bin", 128)
    up_0_block_1_norm2_weight = load_bin(weights_dir + "/decoder_up_0_block_1_norm2_weight.bin", 128)
    up_0_block_2_conv1_bias = load_bin(weights_dir + "/decoder_up_0_block_2_conv1_bias.bin", 128)
    up_0_block_2_conv1_weight = load_bin(weights_dir + "/decoder_up_0_block_2_conv1_weight.bin", 147456)
    up_0_block_2_conv2_bias = load_bin(weights_dir + "/decoder_up_0_block_2_conv2_bias.bin", 128)
    up_0_block_2_conv2_weight = load_bin(weights_dir + "/decoder_up_0_block_2_conv2_weight.bin", 147456)
    up_0_block_2_norm1_bias = load_bin(weights_dir + "/decoder_up_0_block_2_norm1_bias.bin", 128)
    up_0_block_2_norm1_weight = load_bin(weights_dir + "/decoder_up_0_block_2_norm1_weight.bin", 128)
    up_0_block_2_norm2_bias = load_bin(weights_dir + "/decoder_up_0_block_2_norm2_bias.bin", 128)
    up_0_block_2_norm2_weight = load_bin(weights_dir + "/decoder_up_0_block_2_norm2_weight.bin", 128)
    up_1_block_0_conv1_bias = load_bin(weights_dir + "/decoder_up_1_block_0_conv1_bias.bin", 256)
    up_1_block_0_conv1_weight = load_bin(weights_dir + "/decoder_up_1_block_0_conv1_weight.bin", 1179648)
    up_1_block_0_conv2_bias = load_bin(weights_dir + "/decoder_up_1_block_0_conv2_bias.bin", 256)
    up_1_block_0_conv2_weight = load_bin(weights_dir + "/decoder_up_1_block_0_conv2_weight.bin", 589824)
    up_1_block_0_nin_shortcut_bias = load_bin(weights_dir + "/decoder_up_1_block_0_nin_shortcut_bias.bin", 256)
    up_1_block_0_nin_shortcut_weight = load_bin(weights_dir + "/decoder_up_1_block_0_nin_shortcut_weight.bin", 131072)
    up_1_block_0_norm1_bias = load_bin(weights_dir + "/decoder_up_1_block_0_norm1_bias.bin", 512)
    up_1_block_0_norm1_weight = load_bin(weights_dir + "/decoder_up_1_block_0_norm1_weight.bin", 512)
    up_1_block_0_norm2_bias = load_bin(weights_dir + "/decoder_up_1_block_0_norm2_bias.bin", 256)
    up_1_block_0_norm2_weight = load_bin(weights_dir + "/decoder_up_1_block_0_norm2_weight.bin", 256)
    up_1_block_1_conv1_bias = load_bin(weights_dir + "/decoder_up_1_block_1_conv1_bias.bin", 256)
    up_1_block_1_conv1_weight = load_bin(weights_dir + "/decoder_up_1_block_1_conv1_weight.bin", 589824)
    up_1_block_1_conv2_bias = load_bin(weights_dir + "/decoder_up_1_block_1_conv2_bias.bin", 256)
    up_1_block_1_conv2_weight = load_bin(weights_dir + "/decoder_up_1_block_1_conv2_weight.bin", 589824)
    up_1_block_1_norm1_bias = load_bin(weights_dir + "/decoder_up_1_block_1_norm1_bias.bin", 256)
    up_1_block_1_norm1_weight = load_bin(weights_dir + "/decoder_up_1_block_1_norm1_weight.bin", 256)
    up_1_block_1_norm2_bias = load_bin(weights_dir + "/decoder_up_1_block_1_norm2_bias.bin", 256)
    up_1_block_1_norm2_weight = load_bin(weights_dir + "/decoder_up_1_block_1_norm2_weight.bin", 256)
    up_1_block_2_conv1_bias = load_bin(weights_dir + "/decoder_up_1_block_2_conv1_bias.bin", 256)
    up_1_block_2_conv1_weight = load_bin(weights_dir + "/decoder_up_1_block_2_conv1_weight.bin", 589824)
    up_1_block_2_conv2_bias = load_bin(weights_dir + "/decoder_up_1_block_2_conv2_bias.bin", 256)
    up_1_block_2_conv2_weight = load_bin(weights_dir + "/decoder_up_1_block_2_conv2_weight.bin", 589824)
    up_1_block_2_norm1_bias = load_bin(weights_dir + "/decoder_up_1_block_2_norm1_bias.bin", 256)
    up_1_block_2_norm1_weight = load_bin(weights_dir + "/decoder_up_1_block_2_norm1_weight.bin", 256)
    up_1_block_2_norm2_bias = load_bin(weights_dir + "/decoder_up_1_block_2_norm2_bias.bin", 256)
    up_1_block_2_norm2_weight = load_bin(weights_dir + "/decoder_up_1_block_2_norm2_weight.bin", 256)
    up_1_upsample_conv_bias = load_bin(weights_dir + "/decoder_up_1_upsample_conv_bias.bin", 256)
    up_1_upsample_conv_weight = load_bin(weights_dir + "/decoder_up_1_upsample_conv_weight.bin", 589824)
    up_2_block_0_conv1_bias = load_bin(weights_dir + "/decoder_up_2_block_0_conv1_bias.bin", 512)
    up_2_block_0_conv1_weight = load_bin(weights_dir + "/decoder_up_2_block_0_conv1_weight.bin", 2359296)
    up_2_block_0_conv2_bias = load_bin(weights_dir + "/decoder_up_2_block_0_conv2_bias.bin", 512)
    up_2_block_0_conv2_weight = load_bin(weights_dir + "/decoder_up_2_block_0_conv2_weight.bin", 2359296)
    up_2_block_0_norm1_bias = load_bin(weights_dir + "/decoder_up_2_block_0_norm1_bias.bin", 512)
    up_2_block_0_norm1_weight = load_bin(weights_dir + "/decoder_up_2_block_0_norm1_weight.bin", 512)
    up_2_block_0_norm2_bias = load_bin(weights_dir + "/decoder_up_2_block_0_norm2_bias.bin", 512)
    up_2_block_0_norm2_weight = load_bin(weights_dir + "/decoder_up_2_block_0_norm2_weight.bin", 512)
    up_2_block_1_conv1_bias = load_bin(weights_dir + "/decoder_up_2_block_1_conv1_bias.bin", 512)
    up_2_block_1_conv1_weight = load_bin(weights_dir + "/decoder_up_2_block_1_conv1_weight.bin", 2359296)
    up_2_block_1_conv2_bias = load_bin(weights_dir + "/decoder_up_2_block_1_conv2_bias.bin", 512)
    up_2_block_1_conv2_weight = load_bin(weights_dir + "/decoder_up_2_block_1_conv2_weight.bin", 2359296)
    up_2_block_1_norm1_bias = load_bin(weights_dir + "/decoder_up_2_block_1_norm1_bias.bin", 512)
    up_2_block_1_norm1_weight = load_bin(weights_dir + "/decoder_up_2_block_1_norm1_weight.bin", 512)
    up_2_block_1_norm2_bias = load_bin(weights_dir + "/decoder_up_2_block_1_norm2_bias.bin", 512)
    up_2_block_1_norm2_weight = load_bin(weights_dir + "/decoder_up_2_block_1_norm2_weight.bin", 512)
    up_2_block_2_conv1_bias = load_bin(weights_dir + "/decoder_up_2_block_2_conv1_bias.bin", 512)
    up_2_block_2_conv1_weight = load_bin(weights_dir + "/decoder_up_2_block_2_conv1_weight.bin", 2359296)
    up_2_block_2_conv2_bias = load_bin(weights_dir + "/decoder_up_2_block_2_conv2_bias.bin", 512)
    up_2_block_2_conv2_weight = load_bin(weights_dir + "/decoder_up_2_block_2_conv2_weight.bin", 2359296)
    up_2_block_2_norm1_bias = load_bin(weights_dir + "/decoder_up_2_block_2_norm1_bias.bin", 512)
    up_2_block_2_norm1_weight = load_bin(weights_dir + "/decoder_up_2_block_2_norm1_weight.bin", 512)
    up_2_block_2_norm2_bias = load_bin(weights_dir + "/decoder_up_2_block_2_norm2_bias.bin", 512)
    up_2_block_2_norm2_weight = load_bin(weights_dir + "/decoder_up_2_block_2_norm2_weight.bin", 512)
    up_2_upsample_conv_bias = load_bin(weights_dir + "/decoder_up_2_upsample_conv_bias.bin", 512)
    up_2_upsample_conv_weight = load_bin(weights_dir + "/decoder_up_2_upsample_conv_weight.bin", 2359296)
    up_3_block_0_conv1_bias = load_bin(weights_dir + "/decoder_up_3_block_0_conv1_bias.bin", 512)
    up_3_block_0_conv1_weight = load_bin(weights_dir + "/decoder_up_3_block_0_conv1_weight.bin", 2359296)
    up_3_block_0_conv2_bias = load_bin(weights_dir + "/decoder_up_3_block_0_conv2_bias.bin", 512)
    up_3_block_0_conv2_weight = load_bin(weights_dir + "/decoder_up_3_block_0_conv2_weight.bin", 2359296)
    up_3_block_0_norm1_bias = load_bin(weights_dir + "/decoder_up_3_block_0_norm1_bias.bin", 512)
    up_3_block_0_norm1_weight = load_bin(weights_dir + "/decoder_up_3_block_0_norm1_weight.bin", 512)
    up_3_block_0_norm2_bias = load_bin(weights_dir + "/decoder_up_3_block_0_norm2_bias.bin", 512)
    up_3_block_0_norm2_weight = load_bin(weights_dir + "/decoder_up_3_block_0_norm2_weight.bin", 512)
    up_3_block_1_conv1_bias = load_bin(weights_dir + "/decoder_up_3_block_1_conv1_bias.bin", 512)
    up_3_block_1_conv1_weight = load_bin(weights_dir + "/decoder_up_3_block_1_conv1_weight.bin", 2359296)
    up_3_block_1_conv2_bias = load_bin(weights_dir + "/decoder_up_3_block_1_conv2_bias.bin", 512)
    up_3_block_1_conv2_weight = load_bin(weights_dir + "/decoder_up_3_block_1_conv2_weight.bin", 2359296)
    up_3_block_1_norm1_bias = load_bin(weights_dir + "/decoder_up_3_block_1_norm1_bias.bin", 512)
    up_3_block_1_norm1_weight = load_bin(weights_dir + "/decoder_up_3_block_1_norm1_weight.bin", 512)
    up_3_block_1_norm2_bias = load_bin(weights_dir + "/decoder_up_3_block_1_norm2_bias.bin", 512)
    up_3_block_1_norm2_weight = load_bin(weights_dir + "/decoder_up_3_block_1_norm2_weight.bin", 512)
    up_3_block_2_conv1_bias = load_bin(weights_dir + "/decoder_up_3_block_2_conv1_bias.bin", 512)
    up_3_block_2_conv1_weight = load_bin(weights_dir + "/decoder_up_3_block_2_conv1_weight.bin", 2359296)
    up_3_block_2_conv2_bias = load_bin(weights_dir + "/decoder_up_3_block_2_conv2_bias.bin", 512)
    up_3_block_2_conv2_weight = load_bin(weights_dir + "/decoder_up_3_block_2_conv2_weight.bin", 2359296)
    up_3_block_2_norm1_bias = load_bin(weights_dir + "/decoder_up_3_block_2_norm1_bias.bin", 512)
    up_3_block_2_norm1_weight = load_bin(weights_dir + "/decoder_up_3_block_2_norm1_weight.bin", 512)
    up_3_block_2_norm2_bias = load_bin(weights_dir + "/decoder_up_3_block_2_norm2_bias.bin", 512)
    up_3_block_2_norm2_weight = load_bin(weights_dir + "/decoder_up_3_block_2_norm2_weight.bin", 512)
    up_3_upsample_conv_bias = load_bin(weights_dir + "/decoder_up_3_upsample_conv_bias.bin", 512)
    up_3_upsample_conv_weight = load_bin(weights_dir + "/decoder_up_3_upsample_conv_weight.bin", 2359296)

    # conv_in: 16 -> 512
    h_cur = conv2d(latent, conv_in_weight, conv_in_bias, n, 16, 512, h, w, 3, 1, 1)

    # mid blocks
    h_cur = group_norm(h_cur, mid_block_1_norm1_weight, mid_block_1_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, mid_block_1_conv1_weight, mid_block_1_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, mid_block_1_norm2_weight, mid_block_1_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, mid_block_1_conv2_weight, mid_block_1_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, mid_block_2_norm1_weight, mid_block_2_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, mid_block_2_conv1_weight, mid_block_2_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, mid_block_2_norm2_weight, mid_block_2_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, mid_block_2_conv2_weight, mid_block_2_conv2_bias, n, 512, 512, h, w, 3, 1, 1)

    # up blocks (using actual weight shapes)
    # up.1 upsample: 256 -> 256
    # up.2 upsample: 512 -> 512
    # up.3 upsample: 512 -> 512
    h_cur = group_norm(h_cur, up_0_block_0_norm1_weight, up_0_block_0_norm1_bias, 32, 256, h*w)
    arr_silu(h_cur, h_cur, n*256*h*w)
    h_cur = conv2d(h_cur, up_0_block_0_conv1_weight, up_0_block_0_conv1_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_0_block_0_norm2_weight, up_0_block_0_norm2_bias, 32, 256, h*w)
    arr_silu(h_cur, h_cur, n*256*h*w)
    h_cur = conv2d(h_cur, up_0_block_0_conv2_weight, up_0_block_0_conv2_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_0_block_1_norm1_weight, up_0_block_1_norm1_bias, 32, 128, h*w)
    arr_silu(h_cur, h_cur, n*128*h*w)
    h_cur = conv2d(h_cur, up_0_block_1_conv1_weight, up_0_block_1_conv1_bias, n, 128, 128, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_0_block_1_norm2_weight, up_0_block_1_norm2_bias, 32, 128, h*w)
    arr_silu(h_cur, h_cur, n*128*h*w)
    h_cur = conv2d(h_cur, up_0_block_1_conv2_weight, up_0_block_1_conv2_bias, n, 128, 128, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_0_block_2_norm1_weight, up_0_block_2_norm1_bias, 32, 128, h*w)
    arr_silu(h_cur, h_cur, n*128*h*w)
    h_cur = conv2d(h_cur, up_0_block_2_conv1_weight, up_0_block_2_conv1_bias, n, 128, 128, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_0_block_2_norm2_weight, up_0_block_2_norm2_bias, 32, 128, h*w)
    arr_silu(h_cur, h_cur, n*128*h*w)
    h_cur = conv2d(h_cur, up_0_block_2_conv2_weight, up_0_block_2_conv2_bias, n, 128, 128, h, w, 3, 1, 1)
    h_cur = upsample_nearest(h_cur, n, 256, h, w, 2)
    h = h*2; w = w*2
    h_cur = conv2d(h_cur, up_1_upsample_conv_weight, up_1_upsample_conv_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_1_block_0_norm1_weight, up_1_block_0_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_1_block_0_conv1_weight, up_1_block_0_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_1_block_0_norm2_weight, up_1_block_0_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_1_block_0_conv2_weight, up_1_block_0_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_1_block_1_norm1_weight, up_1_block_1_norm1_bias, 32, 256, h*w)
    arr_silu(h_cur, h_cur, n*256*h*w)
    h_cur = conv2d(h_cur, up_1_block_1_conv1_weight, up_1_block_1_conv1_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_1_block_1_norm2_weight, up_1_block_1_norm2_bias, 32, 256, h*w)
    arr_silu(h_cur, h_cur, n*256*h*w)
    h_cur = conv2d(h_cur, up_1_block_1_conv2_weight, up_1_block_1_conv2_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_1_block_2_norm1_weight, up_1_block_2_norm1_bias, 32, 256, h*w)
    arr_silu(h_cur, h_cur, n*256*h*w)
    h_cur = conv2d(h_cur, up_1_block_2_conv1_weight, up_1_block_2_conv1_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_1_block_2_norm2_weight, up_1_block_2_norm2_bias, 32, 256, h*w)
    arr_silu(h_cur, h_cur, n*256*h*w)
    h_cur = conv2d(h_cur, up_1_block_2_conv2_weight, up_1_block_2_conv2_bias, n, 256, 256, h, w, 3, 1, 1)
    h_cur = upsample_nearest(h_cur, n, 512, h, w, 2)
    h = h*2; w = w*2
    h_cur = conv2d(h_cur, up_2_upsample_conv_weight, up_2_upsample_conv_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_2_block_0_norm1_weight, up_2_block_0_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_2_block_0_conv1_weight, up_2_block_0_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_2_block_0_norm2_weight, up_2_block_0_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_2_block_0_conv2_weight, up_2_block_0_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_2_block_1_norm1_weight, up_2_block_1_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_2_block_1_conv1_weight, up_2_block_1_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_2_block_1_norm2_weight, up_2_block_1_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_2_block_1_conv2_weight, up_2_block_1_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_2_block_2_norm1_weight, up_2_block_2_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_2_block_2_conv1_weight, up_2_block_2_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_2_block_2_norm2_weight, up_2_block_2_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_2_block_2_conv2_weight, up_2_block_2_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = upsample_nearest(h_cur, n, 512, h, w, 2)
    h = h*2; w = w*2
    h_cur = conv2d(h_cur, up_3_upsample_conv_weight, up_3_upsample_conv_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_3_block_0_norm1_weight, up_3_block_0_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_3_block_0_conv1_weight, up_3_block_0_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_3_block_0_norm2_weight, up_3_block_0_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_3_block_0_conv2_weight, up_3_block_0_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_3_block_1_norm1_weight, up_3_block_1_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_3_block_1_conv1_weight, up_3_block_1_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_3_block_1_norm2_weight, up_3_block_1_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_3_block_1_conv2_weight, up_3_block_1_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_3_block_2_norm1_weight, up_3_block_2_norm1_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_3_block_2_conv1_weight, up_3_block_2_conv1_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, up_3_block_2_norm2_weight, up_3_block_2_norm2_bias, 32, 512, h*w)
    arr_silu(h_cur, h_cur, n*512*h*w)
    h_cur = conv2d(h_cur, up_3_block_2_conv2_weight, up_3_block_2_conv2_bias, n, 512, 512, h, w, 3, 1, 1)
    h_cur = group_norm(h_cur, norm_out_weight, norm_out_bias, 32, 128, h*w)
    arr_silu(h_cur, h_cur, n*128*h*w)
    out = conv2d(h_cur, conv_out_weight, conv_out_bias, n, 128, 3, h, w, 3, 1, 1)
    arr_clip(out, 0.0, 1.0, n*3*h*w)
    return out
